version: '3.8'

services:
  daemon:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: conversion_service_daemon
    restart: unless-stopped
    command: /start-daemon
    volumes:
      - .:/app
      - /mnt/:/datastore
    env_file:
      - .env/.dev-sample
    environment:
      - FLASK_APP=app
    depends_on:
      - mail_server

  mail_server:
    image: rnwood/smtp4dev:v3
    ports:
      - 5011:80
