"""empty message

Revision ID: 7901f1f8b5bd
Revises: d433d110d594
Create Date: 2022-10-20 22:11:34.145491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7901f1f8b5bd'
down_revision = 'd433d110d594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversion_tasks', sa.Column('celery_task', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversion_tasks', 'celery_task')
    # ### end Alembic commands ###
