"""Initial migration.

Revision ID: d433d110d594
Revises: 
Create Date: 2022-10-13 23:20:02.772568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd433d110d594'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('conversion_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('file_format', sa.Enum('MP3', 'WAV', 'OGG', name='conversiontaskformats'), nullable=False),
    sa.Column('file_new_format', sa.Enum('MP3', 'WAV', 'OGG', name='conversiontaskformats'), nullable=False),
    sa.Column('file_source_path', sa.String(length=250), nullable=False),
    sa.Column('file_converted_path', sa.String(length=250), nullable=False),
    sa.Column('task_status', sa.Enum('UPLOADED', 'PROCESSED', name='conversiontaskstatus'), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversion_tasks')
    op.drop_table('users')
    # ### end Alembic commands ###
